name: Build Wasm & Deploy Static Files
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Check emcc version
        run: emcc -v

      - name: Compile C++ to Wasm
        run: |
          emcc src/main.cpp -o main.js \
            -s EXPORTED_RUNTIME_METHODS='["ccall"]' \
            -s ALLOW_MEMORY_GROWTH=1 \
            -Oz
          # 禁止 Jekyll 处理，保证 wasm 正常
          touch .nojekyll

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4